;
;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( dummy7                    114                     )
  ( dummy1                    115                     )
  ( dummy2                    116                     )
  ( dummy3                    117                     )
  ( dummy4                    118                     )
  ( dummy5                    119                     )
  ( dummy6                    120                     )
  ( slot                      126                     )
  ( dummy                     127                     )
 ;System-Reserved Purposes:
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( drawing                   252        drw          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( ref                       0          ref          )
  ( PWELL                     1          PWELL        )
  ( NWELL                     2          NWELL        )
  ( DIFF                      3          DIFF         )
  ( OD2                       4          OD2          )
  ( N3V                       5          N3V          )
  ( N5V                       6          N5V          )
  ( PIMP                      7          PIMP         )
  ( NIMP                      8          NIMP         )
  ( POLY3                     9          POLY3        )
  ( POLY4                     10         POLY4        )
  ( PDIFF                     11         PDIFF        )
  ( NDIFF                     12         NDIFF        )
  ( POLY1                     13         POLY1        )
  ( POLY2                     14         POLY2        )
  ( CONT                      15         CONT         )
  ( METAL1                    16         METAL1       )
  ( VIA12                     17         VIA12        )
  ( METAL2                    18         METAL2       )
  ( PAD                       19         PAD          )
  ( BPI                       20         BPI          )
  ( VIA67                     21         VIA67        )
  ( METAL7                    22         METAL7       )
  ( VTP                       23         VTP          )
  ( VTN                       24         VTN          )
  ( VTDP                      25         VTDP         )
  ( VTDN                      26         VTDN         )
  ( VIA23                     27         VIA23        )
  ( METAL3                    28         METAL3       )
  ( VIA34                     29         VIA34        )
  ( ESD                       30         ESD          )
  ( METAL4                    31         METAL4       )
  ( VIA45                     32         VIA45        )
  ( METAL5                    33         METAL5       )
  ( RPO                       34         RPO          )
  ( DMEXCL                    35         DMEXCL       )
  ( ESD5V                     36         ESD5V        )
  ( PTDIODE                   37         PTDIODE      )
  ( METAL6                    38         METAL6       )
  ( VIA56                     39         VIA56        )
  ( VIAD                      40         VIAD         )
  ( MD                        41         MD           )
  ( CBD                       42         CBD          )
  ( UBM                       43         UBM          )
  ( IP                        44         IP           )
  ( SLTEXCL                   45         SLTEXCL      )
  ( FUSE                      46         FUSE         )
  ( LPP                       48         LPP          )
  ( BJTDUMMY                  49         BJTDUMM      )
  ( PSUB2                     50         PSUB2        )
  ( HOTWL                     51         HOTWL        )
  ( RWDUMMY                   52         RWDUMMY      )
  ( VCDUMMY                   53         VCDUMMY      )
  ( RPDUMMY                   54         RPDUMMY      )
  ( EXCL                      55         EXCL         )
  ( DIODUMMY                  56         DIODUMM      )
  ( TRAN                      57         TRAN         )
  ( SDI                       58         SDI          )
  ( TEXT                      59         TEXT         )
  ( DRCDUMMY                  60         DRCDUMM      )
  ( N2V                       61         N2V          )
  ( PMDMY                     64         PMDMY        )
  ( DPDUMMY                   65         DPDUMMY      )
  ( PLDUMMY                   66         PLDUMMY      )
  ( CDUMMY                    68         CDUMMY       )
  ( RMDUMMY                   69         RMDUMMY      )
  ( CELLIMP                   70         CELLIMP      )
  ( BC1                       71         BC1          )
  ( BC2                       72         BC2          )
  ( BTC                       73         BTC          )
  ( VCC                       74         VCC          )
  ( RODUMMY                   75         RODUMMY      )
  ( ESEXCL                    76         ESEXCL       )
  ( CPDUMMY                   77         CPDUMMY      )
  ( PDIMP                     78         PDIMP        )
  ( PUIMP                     79         PUIMP        )
  ( CELLBRC1                  80         CELLBRC      )
  ( BLBRC2                    81         BLBRC2       )
  ( DNWELL                    82         DNWELL       )
  ( P1W                       83         P1W          )
  ( P1R                       84         P1R          )
  ( SAC                       85         SAC          )
  ( C1                        86         C1           )
  ( C2                        87         C2           )
  ( DPITCH                    88         DPITCH       )
  ( PLMIDE                    89         PLMIDE       )
  ( NPLUSBL                   90         NPLUSBL      )
  ( PPLUSBL                   91         PPLUSBL      )
  ( CAPP                      92         CAPP         )
  ( PBASE                     93         PBASE        )
  ( HIPRO                     94         HIPRO        )
  ( EMCUT                     95         EMCUT        )
  ( PPBLPROT                  96         PPBLPRO      )
  ( NEPI                      97         NEPI         )
  ( NWELONLY                  98         NWELONL      )
  ( NLDDPROT                  99         NLDDPRO      )
  ( NPLUSPROT                 100        NPLUSPR      )
  ( NOGEN                     101        NOGEN        )
  ( SINKER                    102        SINKER       )
  ( BNP                       124        BNP          )
  ( CPT                       125        CPT          )
  ( CODE                      126        CODE         )
  ( boundary                  127        boundar      )
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        Cannoto      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFen      )
  ( softFence                 206        softFen      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        designF      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLay      )
  ( changedLayer              220        changed      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBound      )
  ( instance                  236        instanc      )
  ( annotate                  237        annotat      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        backgro      )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( ref                       drawing    )
  ( PWELL                     drawing    )
  ( NWELL                     drawing    )
  ( DIFF                      drawing    )
  ( PDIFF                     drawing    )
  ( NDIFF                     drawing    )
  ( OD2                       drawing    )
  ( POLY1                     drawing    )
  ( POLY2                     drawing    )
  ( POLY3                     drawing    )
  ( POLY4                     drawing    )
  ( N2V                       drawing    )
  ( N3V                       drawing    )
  ( N5V                       drawing    )
  ( PIMP                      drawing    )
  ( NIMP                      drawing    )
  ( ESD                       drawing    )
  ( ESD5V                     drawing    )
  ( RPO                       drawing    )
  ( CONT                      drawing    )
  ( METAL1                    drawing    )
  ( VIA12                     drawing    )
  ( METAL2                    drawing    )
  ( VIA23                     drawing    )
  ( METAL3                    drawing    )
  ( VIA34                     drawing    )
  ( METAL4                    drawing    )
  ( VIA45                     drawing    )
  ( METAL5                    drawing    )
  ( VIA56                     drawing    )
  ( METAL6                    drawing    )
  ( VIA67                     drawing    )
  ( METAL7                    drawing    )
  ( PAD                       drawing    )
  ( FUSE                      drawing    )
  ( BPI                       drawing    )
  ( VTP                       drawing    )
  ( VTN                       drawing    )
  ( VTDP                      drawing    )
  ( VTDN                      drawing    )
  ( LPP                       drawing    )
  ( METAL1                    pin        )
  ( METAL2                    pin        )
  ( METAL3                    pin        )
  ( METAL4                    pin        )
  ( METAL5                    pin        )
  ( METAL6                    pin        )
  ( METAL7                    pin        )
  ( POLY1                     pin        )
  ( MD                        pin        )
  ( BJTDUMMY                  drawing    )
  ( PSUB2                     drawing    )
  ( HOTWL                     drawing    )
  ( RWDUMMY                   drawing    )
  ( RPDUMMY                   drawing    )
  ( RMDUMMY                   drawing    )
  ( VCDUMMY                   drawing    )
  ( CDUMMY                    drawing    )
  ( DIODUMMY                  drawing    )
  ( PTDIODE                   drawing    )
  ( EXCL                      drawing    )
  ( TRAN                      drawing    )
  ( SDI                       drawing    )
  ( TEXT                      drawing    )
  ( DRCDUMMY                  drawing    )
  ( DPDUMMY                   drawing    )
  ( PLDUMMY                   drawing    )
  ( marker                    error      )
  ( marker                    warning    )
  ( CELLIMP                   drawing    )
  ( BC1                       drawing    )
  ( BC2                       drawing    )
  ( BTC                       drawing    )
  ( VCC                       drawing    )
  ( RODUMMY                   drawing    )
  ( ESEXCL                    drawing    )
  ( CPDUMMY                   drawing    )
  ( PDIMP                     drawing    )
  ( PUIMP                     drawing    )
  ( CELLBRC1                  drawing    )
  ( BLBRC2                    drawing    )
  ( DNWELL                    drawing    )
  ( P1W                       drawing    )
  ( P1R                       drawing    )
  ( SAC                       drawing    )
  ( C1                        drawing    )
  ( C2                        drawing    )
  ( DPITCH                    drawing    )
  ( PLMIDE                    drawing    )
  ( PMDMY                     drawing    )
  ( METAL1                    net        )
  ( METAL2                    net        )
  ( METAL3                    net        )
  ( METAL4                    net        )
  ( METAL5                    net        )
  ( METAL6                    net        )
  ( METAL7                    net        )
  ( METAL1                    boundary   )
  ( METAL2                    boundary   )
  ( METAL3                    boundary   )
  ( METAL4                    boundary   )
  ( METAL5                    boundary   )
  ( METAL6                    boundary   )
  ( METAL7                    boundary   )
  ( CONT                      net        )
  ( VIA12                     net        )
  ( VIA23                     net        )
  ( VIA34                     net        )
  ( VIA45                     net        )
  ( VIA56                     net        )
  ( VIA67                     net        )
  ( CONT                      boundary   )
  ( VIA12                     boundary   )
  ( VIA23                     boundary   )
  ( VIA34                     boundary   )
  ( VIA45                     boundary   )
  ( VIA56                     boundary   )
  ( VIA67                     boundary   )
  ( prBoundary                drawing    )
  ( prBoundary                label      )
  ( prBoundary                boundary   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( axis                      drawing    )
  ( border                    drawing    )
  ( align                     drawing    )
  ( device                    drawing    )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( device                    label      )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( pin                       label      )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( annotate                  drawing    )
  ( designFlow                drawing    )
  ( annotate                  drawing1   )
  ( designFlow                drawing1   )
  ( annotate                  drawing2   )
  ( designFlow                drawing2   )
  ( annotate                  drawing3   )
  ( designFlow                drawing3   )
  ( annotate                  drawing4   )
  ( designFlow                drawing4   )
  ( annotate                  drawing5   )
  ( designFlow                drawing5   )
  ( annotate                  drawing6   )
  ( designFlow                drawing6   )
  ( annotate                  drawing7   )
  ( designFlow                drawing7   )
  ( annotate                  drawing8   )
  ( designFlow                drawing8   )
  ( annotate                  drawing9   )
  ( designFlow                drawing9   )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( boundary                  drawing    )
  ( Canplace                  drawing    )
  ( background                drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( METAL1                    dummy      )
  ( METAL2                    dummy      )
  ( METAL3                    dummy      )
  ( METAL4                    dummy      )
  ( METAL5                    dummy      )
  ( METAL6                    dummy      )
  ( METAL7                    dummy      )
  ( METAL1                    slot       )
  ( METAL2                    slot       )
  ( METAL3                    slot       )
  ( METAL4                    slot       )
  ( METAL5                    slot       )
  ( METAL6                    slot       )
  ( METAL7                    slot       )
  ( NPLUSBL                   drawing    )
  ( PPLUSBL                   drawing    )
  ( SINKER                    drawing    )
  ( PBASE                     drawing    )
  ( HIPRO                     drawing    )
  ( EMCUT                     drawing    )
  ( PPBLPROT                  drawing    )
  ( NEPI                      drawing    )
  ( NWELONLY                  drawing    )
  ( NLDDPROT                  drawing    )
  ( NPLUSPROT                 drawing    )
  ( NOGEN                     drawing    )
  ( CAPP                      drawing    )
  ( DMEXCL                    dummy1     )
  ( DMEXCL                    dummy2     )
  ( DMEXCL                    dummy3     )
  ( DMEXCL                    dummy4     )
  ( DMEXCL                    dummy5     )
  ( DMEXCL                    dummy6     )
  ( DMEXCL                    dummy7     )
  ( SLTEXCL                   dummy1     )
  ( SLTEXCL                   dummy2     )
  ( SLTEXCL                   dummy3     )
  ( SLTEXCL                   dummy4     )
  ( SLTEXCL                   dummy5     )
  ( SLTEXCL                   dummy6     )
  ( SLTEXCL                   dummy7     )
  ( VIAD                      drawing    )
  ( MD                        drawing    )
  ( CBD                       drawing    )
  ( UBM                       drawing    )
  ( IP                        drawing    )
  ( BNP                       drawing    )
  ( CPT                       drawing    )
  ( CODE                      drawing    )
 ) ;techLayerPurposePriorities



 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( ref          drawing      redhidden_L      t t t t nil )
  ( PWELL        drawing      creamshortDash_L t t t t nil )
  ( NWELL        drawing      creamthickLine2_L t t t t t )
  ( DIFF         drawing      redbackSlash_S   t t t t t )
  ( PDIFF        drawing      reddot3_S        t t t t nil )
  ( NDIFF        drawing      orangedots_S     t t t t nil )
  ( OD2          drawing      winColor2winColor1daggerthickLine t t t t t )
  ( POLY1        drawing      bluecrossthickLine t t t t t )
  ( POLY2        drawing      pinkbrick_SN     t t t t t )
  ( POLY3        drawing      limedot4_S       t t t t nil )
  ( POLY4        drawing      limedot3_S       t t t t nil )
  ( N2V          drawing      grayshortDash_L  t t t t nil )
  ( N3V          drawing      graythickLine2_L t t t t nil )
  ( N5V          drawing      graythickLine_L  t t t t t )
  ( PIMP         drawing      magenta          t t t t t )
  ( NIMP         drawing      gray             t t t t t )
  ( ESD          drawing      white            t t t t t )
  ( ESD5V        drawing      white            t t t t t )
  ( RPO          drawing      forest           t t t t nil )
  ( CONT         drawing      greencross_S     t t t t t )
  ( METAL1       drawing      cyandot4_S       t t t t t )
  ( VIA12        drawing      yellowX_S        t t t t t )
  ( METAL2       drawing      goldstipple0_S   t t t t t )
  ( VIA23        drawing      yellowhLine_S    t t t t t )
  ( METAL3       drawing      forestdot4_S     t t t t t )
  ( VIA34        drawing      purplevLine_S    t t t t t )
  ( METAL4       drawing      slatedot4_S      t t t t t )
  ( VIA45        drawing      whitetriangle_S  t t t t nil )
  ( METAL5       drawing      winColor3dot3_S  t t t t nil )
  ( VIA56        drawing      creamslash_S     t t t t nil )
  ( METAL6       drawing      tanstipple3_S    t t t t nil )
  ( VIA67        drawing      goldx_S          t t t t nil )
  ( METAL7       drawing      limedot4_S       t t t t nil )
  ( PAD          drawing      orangedots_S     t t t t t )
  ( FUSE         drawing      magentadots_S    t t t t nil )
  ( BPI          drawing      magentathickLine2_L t t t t nil )
  ( VTP          drawing      tanshortDash_L   t t t t nil )
  ( VTN          drawing      tanthickLine2_L  t t t t nil )
  ( VTDP         drawing      tanshortDash_L   t t t t nil )
  ( VTDN         drawing      tanthickLine2_L  t t t t nil )
  ( LPP          drawing      magentadot2_S    t t t t nil )
  ( METAL1       pin          cyanXthickLine2  t t t nil t )
  ( METAL2       pin          goldXthickLine2  t t t nil t )
  ( METAL3       pin          forestXthickLine2 t t t nil t )
  ( METAL4       pin          slateXthickLine2 t t t nil t )
  ( METAL5       pin          winColor3XthickLine2 t t t nil nil )
  ( METAL6       pin          tanXthickLine2   t t t nil nil )
  ( METAL7       pin          limeXthickLine2  t t t nil nil )
  ( POLY1        pin          blueXthickLine   t t t nil nil )
  ( MD           pin          tanXthickLine2   t t t nil nil )
  ( BJTDUMMY     drawing      bjtdmy_ptn       t t t t t )
  ( PSUB2        drawing      whiteX_S         t t t t t )
  ( HOTWL        drawing      orangeX_S        t t t t t )
  ( RWDUMMY      drawing      nwresdmy_ptn     t t t t t )
  ( RPDUMMY      drawing      presdmy_ptn      t t t t t )
  ( RMDUMMY      drawing      mresdmy_ptn      t t t t t )
  ( VCDUMMY      drawing      pinkdaggerdashed t t t t nil )
  ( CDUMMY       drawing      capdmy_ptn       t t t t t )
  ( DIODUMMY     drawing      diodedmy_ptn     t t t t t )
  ( PTDIODE      drawing      ptdiodmy_ptn     t t t t t )
  ( EXCL         drawing      greentriangle_S  t t t t t )
  ( TRAN         drawing      navydashed_L     t t t t nil )
  ( SDI          drawing      white            t t t t t )
  ( TEXT         drawing      white            t t t t t )
  ( DRCDUMMY     drawing      white            t t t t t )
  ( DPDUMMY      drawing      navy             t t t t nil )
  ( PLDUMMY      drawing      pink             t t t t nil )
  ( marker       error        whiteX_SB        t t t t t )
  ( marker       warning      yellowX_SB       t t t t t )
  ( CELLIMP      drawing      white            t t t t nil )
  ( BC1          drawing      white            t t t t nil )
  ( BC2          drawing      white            t t t t nil )
  ( BTC          drawing      white            t t t t nil )
  ( VCC          drawing      white            t t t t nil )
  ( RODUMMY      drawing      white            t t t t t )
  ( ESEXCL       drawing      white            t t t t nil )
  ( CPDUMMY      drawing      white            t t t t nil )
  ( PDIMP        drawing      white            t t t t nil )
  ( PUIMP        drawing      white            t t t t nil )
  ( CELLBRC1     drawing      white            t t t t nil )
  ( BLBRC2       drawing      white            t t t t nil )
  ( DNWELL       drawing      tan              t t t t nil )
  ( P1W          drawing      greendot3_S      t t t t nil )
  ( P1R          drawing      yellowdaggerthickLine2 t t t t nil )
  ( SAC          drawing      white            t t t t nil )
  ( C1           drawing      creamstipple0_S  t t t t nil )
  ( C2           drawing      limestipple0_S   t t t t nil )
  ( DPITCH       drawing      white            t t t t nil )
  ( PLMIDE       drawing      white            t t t t nil )
  ( PMDMY        drawing      white            t t t t nil )
  ( METAL1       net          cyanX_S          t t t nil nil )
  ( METAL2       net          yellowX_S        t t t nil nil )
  ( METAL3       net          greenX_S         t t t nil nil )
  ( METAL4       net          cyanX_S          t t t nil nil )
  ( METAL5       net          whiteX_S         t t t nil nil )
  ( METAL6       net          whiteX_S         t t t nil nil )
  ( METAL7       net          whiteX_S         t t t nil nil )
  ( METAL1       boundary     cyandot4_S       t t t nil nil )
  ( METAL2       boundary     yellowdot4_S     t t t nil nil )
  ( METAL3       boundary     greendot4_S      t t t nil nil )
  ( METAL4       boundary     cyandot4_S       t t t nil nil )
  ( METAL5       boundary     whitedot4_S      t t t nil nil )
  ( METAL6       boundary     whitedot4_S      t t t nil nil )
  ( METAL7       boundary     whitedot4_S      t t t nil nil )
  ( CONT         net          limeX_S          t t t nil nil )
  ( VIA12        net          magentaX_S       t t t nil nil )
  ( VIA23        net          yellowX_S        t t t nil nil )
  ( VIA34        net          blueX_S          t t t nil nil )
  ( VIA45        net          whiteX_S         t t t nil nil )
  ( VIA56        net          whiteX_S         t t t nil nil )
  ( VIA67        net          whiteX_S         t t t nil nil )
  ( CONT         boundary     limesolid_S      t t t nil nil )
  ( VIA12        boundary     magentasolid_S   t t t nil nil )
  ( VIA23        boundary     yellowsolid_S    t t t nil nil )
  ( VIA34        boundary     bluesolid_S      t t t nil nil )
  ( VIA45        boundary     white            t t t nil nil )
  ( VIA56        boundary     white            t t t nil nil )
  ( VIA67        boundary     white            t t t nil nil )
  ( prBoundary   drawing      purple           t t t t nil )
  ( prBoundary   label        purple           t t t t nil )
  ( prBoundary   boundary     purpledashed_L   t t t t nil )
  ( instance     drawing      red              t t t t nil )
  ( instance     label        gold             t t t t nil )
  ( hilite       drawing      white            t t t t nil )
  ( hilite       drawing1     magenta          t t t t nil )
  ( hilite       drawing2     tan              t t t t nil )
  ( hilite       drawing3     cyan             t t t t nil )
  ( hilite       drawing4     orange           t t t t nil )
  ( hilite       drawing5     lime             t t t t nil )
  ( hilite       drawing6     orange           t t t t nil )
  ( hilite       drawing7     cream            t t t t nil )
  ( hilite       drawing8     magenta          t t t t nil )
  ( hilite       drawing9     pink             t t t t nil )
  ( y0           drawing      winColor5dashed_LB t t t t nil )
  ( y1           drawing      browndashed_LB   t t t t nil )
  ( y2           drawing      reddashed_LB     t t t t nil )
  ( y3           drawing      pinkdashed_LB    t t t t nil )
  ( y4           drawing      orangedashed_LB  t t t t nil )
  ( y5           drawing      greendashed_LB   t t t t nil )
  ( y6           drawing      bluedashed_LB    t t t t nil )
  ( y7           drawing      purpledashed_LB  t t t t nil )
  ( y8           drawing      golddashed_LB    t t t t nil )
  ( y9           drawing      silverdashed_LB  t t t t nil )
  ( grid         drawing      white            t nil t nil nil )
  ( grid         drawing1     white            t nil t nil nil )
  ( axis         drawing      white            t nil t t nil )
  ( border       drawing      tan              t t t t nil )
  ( align        drawing      tan              t t t t nil )
  ( device       drawing      green            t t t t nil )
  ( device       drawing1     greensolid_S     t t t t nil )
  ( device       drawing2     greendashed_L    t t t t nil )
  ( device       annotate     yellow           t t t t nil )
  ( device       label        green            t t t t nil )
  ( wire         drawing      graysolid_S      t t t t nil )
  ( wire         label        graysolid_S      t t t t nil )
  ( wire         flight       reddashed_L      t t t t nil )
  ( select       drawing      tan              t t t t nil )
  ( drive        drawing      blue             t t t t nil )
  ( hiz          drawing      orange           t t t t nil )
  ( pin          drawing      redsolid_S       t t t t nil )
  ( pin          annotate     red              t t t t nil )
  ( pin          label        red              t t t t nil )
  ( resist       drawing      cyan             t t t t nil )
  ( spike        drawing      purple           t t t t nil )
  ( supply       drawing      lime             t t t t nil )
  ( unknown      drawing      yellow           t t t t nil )
  ( unset        drawing      forest           t t t t nil )
  ( annotate     drawing      orange           t t t t nil )
  ( designFlow   drawing      greensolid_S     t t t nil nil )
  ( annotate     drawing1     pink             t t t t nil )
  ( designFlow   drawing1     redsolid_S       t t t nil nil )
  ( annotate     drawing2     lime             t t t t nil )
  ( designFlow   drawing2     purplesolid_S    t t t nil nil )
  ( annotate     drawing3     cyan             t t t t nil )
  ( designFlow   drawing3     pinksolid_S      t t t nil nil )
  ( annotate     drawing4     yellow           t t t t nil )
  ( designFlow   drawing4     blacksolid_S     t t t nil nil )
  ( annotate     drawing5     white            t t t t nil )
  ( designFlow   drawing5     silversolid_S    t t t nil nil )
  ( annotate     drawing6     silver           t t t t nil )
  ( designFlow   drawing6     tansolid_S       t t t nil nil )
  ( annotate     drawing7     red              t t t t nil )
  ( designFlow   drawing7     cyansolid_S      t t t nil nil )
  ( annotate     drawing8     tan              t t t t nil )
  ( designFlow   drawing8     navysolid_S      t t t nil nil )
  ( annotate     drawing9     green            t t t t nil )
  ( designFlow   drawing9     orangesolid_S    t t t nil nil )
  ( edgeLayer    drawing      winColor5_B      t t t t nil )
  ( edgeLayer    pin          yellow           t t t t nil )
  ( changedLayer tool0        red              nil nil t nil nil )
  ( changedLayer tool1        yellow           nil nil t nil nil )
  ( snap         drawing      yellow           t t t t nil )
  ( stretch      drawing      yellow           t t t t nil )
  ( Row          drawing      cyan             t t t t nil )
  ( Row          label        cyan             t nil t t nil )
  ( Group        drawing      greendots_S      t t t t nil )
  ( Group        label        green            t nil t t nil )
  ( Cannotoccupy drawing      redXthickLine    t t t t nil )
  ( Cannotoccupy boundary     redthickLine_L   t t t t nil )
  ( boundary     drawing      reddashed_L      t t t t nil )
  ( Canplace     drawing      cyan             t t t t nil )
  ( background   drawing      blacksolid_S     t nil t nil nil )
  ( text         drawing      white            t t t t nil )
  ( text         drawing1     whitedashed_L    t t t t nil )
  ( text         drawing2     whitesolid_S     t t t t nil )
  ( Unrouted     drawing      winColor5dashed_L t t t t nil )
  ( Unrouted     drawing1     browndashed_L    t t t t nil )
  ( Unrouted     drawing2     reddashed_L      t t t t nil )
  ( Unrouted     drawing3     pinkdashed_L     t t t t nil )
  ( Unrouted     drawing4     orangedashed_L   t t t t nil )
  ( Unrouted     drawing5     greendashed_L    t t t t nil )
  ( Unrouted     drawing6     bluedashed_L     t t t t nil )
  ( Unrouted     drawing7     purpledashed_L   t t t t nil )
  ( Unrouted     drawing8     golddashed_L     t t t t nil )
  ( Unrouted     drawing9     silverdashed_L   t t t t nil )
  ( hardFence    drawing      red              t t t t nil )
  ( softFence    drawing      yellow           t t t t nil )
  ( METAL1       dummy        cyandot4thickLine2 t t t t nil )
  ( METAL2       dummy        golddot4thickLine2 t t t t nil )
  ( METAL3       dummy        forestdot4thickLine2 t t t t nil )
  ( METAL4       dummy        slatedot4thickLine2 t t t t nil )
  ( METAL5       dummy        winColor3dot4thickLine2 t t t t nil )
  ( METAL6       dummy        tandot4thickLine2 t t t t nil )
  ( METAL7       dummy        limedot4thickLine2 t t t t nil )
  ( METAL1       slot         cyandot4shortDash t t t t nil )
  ( METAL2       slot         golddot4shortDash t t t t nil )
  ( METAL3       slot         forestdot4shortDash t t t t nil )
  ( METAL4       slot         slatedot4shortDash t t t t nil )
  ( METAL5       slot         winColor3dot4shortDash t t t t nil )
  ( METAL6       slot         tandot4shortDash t t t t nil )
  ( METAL7       slot         limedot4shortDash t t t t nil )
  ( NPLUSBL      drawing      pinkdaggerdashed t t t t nil )
  ( PPLUSBL      drawing      navydaggerdashed t t t t nil )
  ( SINKER       drawing      winColor4brickdashDot t t t t nil )
  ( PBASE        drawing      white            t t t t nil )
  ( HIPRO        drawing      limedot4shortDash t t t t nil )
  ( EMCUT        drawing      forestdot4thickLine2 t t t t nil )
  ( PPBLPROT     drawing      orangedots_S     t t t t nil )
  ( NEPI         drawing      tanstipple3_S    t t t t nil )
  ( NWELONLY     drawing      pinksolidthickLine2 t t t t nil )
  ( NLDDPROT     drawing      limedot4thickLine2 t t t t nil )
  ( NPLUSPROT    drawing      joy1brickdashDot t t t t nil )
  ( NOGEN        drawing      slatedot4shortDash t t t t nil )
  ( CAPP         drawing      white            t t nil t nil )
  ( DMEXCL       dummy1       white            t t t t nil )
  ( DMEXCL       dummy2       white            t t t t nil )
  ( DMEXCL       dummy3       white            t t t t nil )
  ( DMEXCL       dummy4       white            t t t t nil )
  ( DMEXCL       dummy5       white            t t t t nil )
  ( DMEXCL       dummy6       white            t t t t nil )
  ( DMEXCL       dummy7       white            t t t t nil )
  ( SLTEXCL      dummy1       green            t t t t nil )
  ( SLTEXCL      dummy2       orange           t t t t nil )
  ( SLTEXCL      dummy3       green            t t t t nil )
  ( SLTEXCL      dummy4       orange           t t t t nil )
  ( SLTEXCL      dummy5       green            t t t t nil )
  ( SLTEXCL      dummy6       orange           t t t t nil )
  ( SLTEXCL      dummy7       green            t t t t nil )
  ( VIAD         drawing      goldx_S          t t t t nil )
  ( MD           drawing      limedot4_S       t t t t nil )
  ( CBD          drawing      orangedots_S     t t t t nil )
  ( UBM          drawing      tanstipple3_S    t t t t nil )
  ( IP           drawing      white            t t nil t nil )
  ( BNP          drawing      pinkdot4thickLine2 t t t t nil )
  ( CPT          drawing      winColor5dot4thickLine2 t t t t nil )
  ( CODE         drawing      violetdot4thickLine2 t t t t nil )
 ) ;techDisplays

techLayerProperties(
;( PropName               Layer1 [ Layer2 ]            PropValue )
 ( routingPitch           METAL1                         1.250000 )
 ( routingPitch           METAL2                         1.400000 )
 ( routingPitch           METAL3                         1.250000 )
 ( routingPitch           METAL4                         1.400000 )
)

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 streamLayers(
 ;( layer       streamNumber    dataType        translate )
 ;( -----       ------------    --------        --------- )
  ( ("ref" "drawing")	0         	0       	nil	 )
  ( ("PWELL" "drawing")	1         	0       	t	 )
  ( ("NWELL" "drawing")	2         	0       	t	 )
  ( ("DIFF" "drawing")	3         	0       	t	 )
  ( ("PDIFF" "drawing")	11        	0       	t	 )
  ( ("NDIFF" "drawing")	12        	0       	t	 )
  ( ("OD2" "drawing")	4         	0       	t	 )
  ( ("POLY1" "drawing")	13        	0       	t	 )
  ( ("POLY2" "drawing")	14        	0       	t	 )
  ( ("POLY3" "drawing")	9         	0       	t	 )
  ( ("POLY4" "drawing")	10        	0       	t	 )
  ( ("N2V" "drawing")	61        	0       	t	 )
  ( ("N3V" "drawing")	5         	0       	t	 )
  ( ("N5V" "drawing")	6         	0       	t	 )
  ( ("PIMP" "drawing")	7         	0       	t	 )
  ( ("NIMP" "drawing")	8         	0       	t	 )
  ( ("ESD" "drawing")	30        	0       	t	 )
  ( ("ESD5V" "drawing")	36        	0       	t	 )
  ( ("RPO" "drawing")	34        	0       	t	 )
  ( ("CONT" "drawing")	15        	0       	t	 )
  ( ("METAL1" "drawing")	16        	0       	t	 )
  ( ("VIA12" "drawing")	17        	0       	t	 )
  ( ("METAL2" "drawing")	18        	0       	t	 )
  ( ("VIA23" "drawing")	27        	0       	t	 )
  ( ("METAL3" "drawing")	28        	0       	t	 )
  ( ("VIA34" "drawing")	29        	0       	t	 )
  ( ("METAL4" "drawing")	31        	0       	t	 )
  ( ("VIA45" "drawing")	32        	0       	t	 )
  ( ("METAL5" "drawing")	33        	0       	t	 )
  ( ("VIA56" "drawing")	39        	0       	t	 )
  ( ("METAL6" "drawing")	38        	0       	t	 )
  ( ("VIA67" "drawing")	21        	0       	t	 )
  ( ("METAL7" "drawing")	22        	0       	t	 )
  ( ("PAD" "drawing")	19        	0       	t	 )
  ( ("FUSE" "drawing")	235       	0       	t	 )
  ( ("BPI" "drawing")	20        	0       	t	 )
  ( ("VTP" "drawing")	23        	0       	t	 )
  ( ("VTN" "drawing")	24        	0       	t	 )
  ( ("VTDP" "drawing")	25        	0       	t	 )
  ( ("VTDN" "drawing")	26        	0       	t	 )
  ( ("LPP" "drawing")	48        	0       	t	 )
  ( ("METAL1" "pin")	40        	0       	t	 )
  ( ("METAL2" "pin")	41        	0       	t	 )
  ( ("METAL3" "pin")	42        	0       	t	 )
  ( ("METAL4" "pin")	43        	0       	t	 )
  ( ("METAL5" "pin")	44        	0       	t	 )
  ( ("METAL6" "pin")	45        	0       	t	 )
  ( ("METAL7" "pin")	46        	0       	t	 )
  ( ("POLY1" "pin")	47        	0       	t	 )
  ( ("MD" "pin")	159       	0       	t	 )
  ( ("BJTDUMMY" "drawing")	49        	0       	t	 )
  ( ("PSUB2" "drawing")	50        	0       	t	 )
  ( ("HOTWL" "drawing")	51        	0       	t	 )
  ( ("RWDUMMY" "drawing")	52        	0       	t	 )
  ( ("RPDUMMY" "drawing")	54        	0       	t	 )
  ( ("RMDUMMY" "drawing")	69        	0       	t	 )
  ( ("VCDUMMY" "drawing")	53        	0       	t	 )
  ( ("CDUMMY" "drawing")	68        	0       	t	 )
  ( ("DIODUMMY" "drawing")	56        	0       	t	 )
  ( ("PTDIODE" "drawing")	37        	0       	t	 )
  ( ("EXCL" "drawing")	55        	0       	t	 )
  ( ("TRAN" "drawing")	57        	0       	t	 )
  ( ("SDI" "drawing")	58        	0       	t	 )
  ( ("TEXT" "drawing")	59        	0       	t	 )
  ( ("DRCDUMMY" "drawing")	60        	0       	t	 )
  ( ("DPDUMMY" "drawing")	65        	0       	t	 )
  ( ("PLDUMMY" "drawing")	66        	0       	t	 )
  ( ("CELLIMP" "drawing")	70        	0       	t	 )
  ( ("BC1" "drawing")	71        	0       	t	 )
  ( ("BC2" "drawing")	72        	0       	t	 )
  ( ("BTC" "drawing")	73        	0       	t	 )
  ( ("VCC" "drawing")	74        	0       	t	 )
  ( ("RODUMMY" "drawing")	75        	0       	t	 )
  ( ("ESEXCL" "drawing")	76        	0       	t	 )
  ( ("CPDUMMY" "drawing")	77        	0       	t	 )
  ( ("PDIMP" "drawing")	78        	0       	t	 )
  ( ("PUIMP" "drawing")	79        	0       	t	 )
  ( ("CELLBRC1" "drawing")	80        	0       	t	 )
  ( ("BLBRC2" "drawing")	81        	0       	t	 )
  ( ("DNWELL" "drawing")	82        	0       	t	 )
  ( ("P1W" "drawing")	83        	0       	t	 )
  ( ("P1R" "drawing")	84        	0       	t	 )
  ( ("SAC" "drawing")	85        	0       	t	 )
  ( ("C1" "drawing")	86        	0       	t	 )
  ( ("C2" "drawing")	87        	0       	t	 )
  ( ("DPITCH" "drawing")	88        	0       	t	 )
  ( ("PLMIDE" "drawing")	89        	0       	t	 )
  ( ("PMDMY" "drawing")	236       	0       	t	 )
  ( ("METAL1" "net")	0         	0       	nil	 )
  ( ("METAL2" "net")	0         	0       	nil	 )
  ( ("METAL3" "net")	0         	0       	nil	 )
  ( ("METAL4" "net")	0         	0       	nil	 )
  ( ("METAL5" "net")	0         	0       	nil	 )
  ( ("METAL6" "net")	0         	0       	nil	 )
  ( ("METAL7" "net")	0         	0       	nil	 )
  ( ("METAL1" "boundary")	151       	0       	nil	 )
  ( ("METAL2" "boundary")	152       	0       	nil	 )
  ( ("METAL3" "boundary")	153       	0       	nil	 )
  ( ("METAL4" "boundary")	154       	0       	nil	 )
  ( ("METAL5" "boundary")	155       	0       	nil	 )
  ( ("METAL6" "boundary")	156       	0       	nil	 )
  ( ("METAL7" "boundary")	157       	0       	nil	 )
  ( ("CONT" "net")	0         	0       	nil	 )
  ( ("VIA12" "net")	0         	0       	nil	 )
  ( ("VIA23" "net")	0         	0       	nil	 )
  ( ("VIA34" "net")	0         	0       	nil	 )
  ( ("VIA45" "net")	0         	0       	nil	 )
  ( ("VIA56" "net")	0         	0       	nil	 )
  ( ("VIA67" "net")	0         	0       	nil	 )
  ( ("CONT" "boundary")	0         	0       	nil	 )
  ( ("VIA12" "boundary")	161       	0       	nil	 )
  ( ("VIA23" "boundary")	162       	0       	nil	 )
  ( ("VIA34" "boundary")	163       	0       	nil	 )
  ( ("VIA45" "boundary")	164       	0       	nil	 )
  ( ("VIA56" "boundary")	165       	0       	nil	 )
  ( ("VIA67" "boundary")	166       	0       	nil	 )
  ( ("prBoundary" "drawing")	62        	0       	t	 )
  ( ("boundary" "drawing")	0         	0       	nil	 )
  ( ("METAL1" "dummy")	16        	1       	t	 )
  ( ("METAL2" "dummy")	18        	1       	t	 )
  ( ("METAL3" "dummy")	28        	1       	t	 )
  ( ("METAL4" "dummy")	31        	1       	t	 )
  ( ("METAL5" "dummy")	33        	1       	t	 )
  ( ("METAL6" "dummy")	38        	1       	t	 )
  ( ("METAL7" "dummy")	22        	1       	t	 )
  ( ("METAL1" "slot")	16        	2       	t	 )
  ( ("METAL2" "slot")	18        	2       	t	 )
  ( ("METAL3" "slot")	28        	2       	t	 )
  ( ("METAL4" "slot")	31        	2       	t	 )
  ( ("METAL5" "slot")	33        	2       	t	 )
  ( ("METAL6" "slot")	38        	2       	t	 )
  ( ("METAL7" "slot")	22        	2       	t	 )
  ( ("NPLUSBL" "drawing")	179       	0       	t	 )
  ( ("PPLUSBL" "drawing")	180       	0       	t	 )
  ( ("SINKER" "drawing")	181       	0       	t	 )
  ( ("PBASE" "drawing")	182       	0       	t	 )
  ( ("HIPRO" "drawing")	183       	0       	t	 )
  ( ("EMCUT" "drawing")	186       	0       	t	 )
  ( ("PPBLPROT" "drawing")	187       	0       	t	 )
  ( ("NEPI" "drawing")	188       	0       	t	 )
  ( ("NWELONLY" "drawing")	189       	0       	t	 )
  ( ("NLDDPROT" "drawing")	231       	0       	t	 )
  ( ("NPLUSPROT" "drawing")	232       	0       	t	 )
  ( ("NOGEN" "drawing")	233       	0       	t	 )
  ( ("CAPP" "drawing")	92        	0       	t	 )
  ( ("DMEXCL" "dummy1")	150       	1       	t	 )
  ( ("DMEXCL" "dummy2")	150       	2       	t	 )
  ( ("DMEXCL" "dummy3")	150       	3       	t	 )
  ( ("DMEXCL" "dummy4")	150       	4       	t	 )
  ( ("DMEXCL" "dummy5")	150       	5       	t	 )
  ( ("DMEXCL" "dummy6")	150       	6       	t	 )
  ( ("DMEXCL" "dummy7")	150       	7       	t	 )
  ( ("SLTEXCL" "dummy1")	158       	1       	t	 )
  ( ("SLTEXCL" "dummy2")	158       	2       	t	 )
  ( ("SLTEXCL" "dummy3")	158       	3       	t	 )
  ( ("SLTEXCL" "dummy4")	158       	4       	t	 )
  ( ("SLTEXCL" "dummy5")	158       	5       	t	 )
  ( ("SLTEXCL" "dummy6")	158       	6       	t	 )
  ( ("SLTEXCL" "dummy7")	158       	7       	t	 )
  ( ("VIAD" "drawing")	167       	0       	t	 )
  ( ("MD" "drawing")	168       	0       	t	 )
  ( ("CBD" "drawing")	169       	0       	t	 )
  ( ("UBM" "drawing")	170       	0       	t	 )
  ( ("IP" "drawing")	63        	63      	t	 )
  ( ("BNP" "drawing")	214       	0       	t	 )
  ( ("CPT" "drawing")	215       	0       	t	 )
  ( ("CODE" "drawing")	216       	0       	t	 )
  ( METAL1    	0         	0       	nil	 )
  ( METAL2    	0         	0       	nil	 )
  ( METAL3    	0         	0       	nil	 )
  ( METAL4    	0         	0       	nil	 )
 ) ;streamLayers

) ;layerRules


;********************************
; PHYSICAL RULES
;********************************
physicalRules(

 spacingRules(
 ;( rule                	layer1    	layer2    	value    )
 ;( ----                	------    	------    	-----    )
  ( minSpacing          	"METAL1"			0.45	 )
  ( minSpacing          	"METAL2"			0.5	 )
  ( minSpacing          	"METAL3"			0.5	 )
  ( minSpacing          	"METAL4"			0.6	 )
  ( minWidth            	"METAL1"			0.5	 )
  ( minWidth            	"METAL2"			0.6	 )
  ( minWidth            	"METAL3"			0.6	 )
  ( minWidth            	"METAL4"			0.6	 )
  ( sameNet             	"METAL1"		"METAL1"		0.45	 )
  ( sameNet             	"METAL2"		"METAL2"		0.5	 )
  ( sameNet             	"METAL3"		"METAL3"		0.5	 )
  ( sameNet             	"METAL4"		"METAL4"		0.6	 )
  ( sameNet             	"VIA12"		"CONT"		0	 )
  ( sameNet             	"VIA23"		"VIA12"		0	 )
  ( sameNet             	"VIA34"		"VIA23"		0	 )
 ) ;spacingRules

 mfgGridResolution(
      ( 0.001000 )
 ) ;mfgGridResolution

) ;physicalRules


;********************************
; ELECTRICAL RULES
;********************************
electricalRules(

 characterizationRules(
 ;( rule                	layer1    	layer2    	value    )
 ;( ----                	------    	------    	-----    )
  ( areaCap             	"METAL1"			3.12e-05	 )
  ( areaCap             	"METAL2"			1.28e-05	 )
  ( areaCap             	"METAL3"			8.116666e-06	 )
  ( areaCap             	"METAL4"			5.933333e-06	 )
  ( sheetRes            	"METAL1"			0.07	 )
  ( sheetRes            	"METAL2"			0.07	 )
  ( sheetRes            	"METAL3"			0.07	 )
  ( sheetRes            	"METAL4"			0.04	 )
 ) ;characterizationRules

) ;electricalRules


;********************************
; DEVICES
;********************************
devices(

tcCreateCDSDeviceClass()

;
; no syEnhancement devices
;

;
; no syDepletion devices
;

symContactDevice(
; (name viaLayer viaPurpose layer1 purpose1 layer2 purpose2
;  w l (row column xPitch yPitch xBias yBias) encByLayer1 encByLayer2 legalRegion)

  (M1_POLY1 CONT drawing POLY1 drawing METAL1 drawing
  0.4 0.4 (1 1 1 1 center center) 0.2 0.15 _NA_)

  (M1_P CONT drawing DIFF drawing METAL1 drawing (PIMP drawing 0.25)
  0.4 0.4 (1 1 1 1 center center) 0.25 0.15 _NA_)

  (M1_N CONT drawing DIFF drawing METAL1 drawing (NIMP drawing 0.25)
  0.4 0.4 (1 1 1 1 center center) 0.25 0.15 _NA_)

  (M2_M1 VIA12 drawing METAL1 drawing METAL2 drawing
  0.5 0.5 (1 1 1 1 center center) 0.2 0.15 _NA_)

  (M3_M2 VIA23 drawing METAL2 drawing METAL3 drawing
  0.5 0.5 (1 1 1 1 center center) 0.2 0.15 _NA_)

  (M4_M3 VIA34 drawing METAL3 drawing METAL4 drawing
  0.5 0.5 (1 1 1 1 center center) 0.2 0.15 _NA_)
)

tfcDefineDeviceProp(
; (viewName        deviceName        propName          propValue)
  (symbolic        M1_POLY1          viaType           "default")
  (symbolic        M1_P              viaType           "default")
  (symbolic        M1_N              viaType           "default")
  (symbolic        M2_M1             viaType           "default")
  (symbolic        M3_M2             viaType           "default")
  (symbolic        M4_M3             viaType           "default")
)

symPinDevice(
; (name maskable layer1 purpose1 w1 layer2 purpose2 w2 legalRegion)
  (METAL1_T nil METAL1 drawing 0.32 _NA_ _NA_ _NA_ _NA_)
  (METAL2_T nil METAL2 drawing 0.4 _NA_ _NA_ _NA_ _NA_)
  (METAL3_T nil METAL3 drawing 0.4 _NA_ _NA_ _NA_ _NA_)
  (METAL4_T nil METAL4 drawing 0.4 _NA_ _NA_ _NA_ _NA_)
)

;
; no ruleContact devices
;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Opus Symbolic Device Class Definition
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;
; no other device classes
;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Opus Symbolic Device Declaration
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;
; no other devices
;
) ;devices


;********************************
; COMPACTOR RULES
;********************************
compactorRules(

 compactorLayers(
 ;( layer                    	usage      )
 ;( -----                    	-----      )
  ( METAL1                   	"conduction" )
  ( METAL2                   	"conduction" )
  ( METAL3                   	"conduction" )
  ( METAL4                   	"conduction" )
 ) ;compactorLayers

) ;compactorRules


;********************************
; DLE RULES
;********************************
dleRules(

 dleExtractLayers(
 ;( list of layers or layer/purpose pairs  )
 ;( -------------------------------------  )
 ) ;dleExtractLayers

 dleNoOverlapLayers(
 ;( forbidden overlaps in DLE )
 ;( ------------------------- )
 ) ;dleNoOverlapLayers

) ;dleRules


;********************************
; DLR RULES
;********************************
dlrRules(

 dlrStackVias(
 ;( viaLayerPairList    stackable )
 ;( ----------------    --------- )
 ) ;dlrStackVias

 dlrRoutingLayers(
 ;( layer                       direction    )
 ;( -----                       ---------    )
 ) ;dlrRoutingLayers

 dlrDevices(
 ;( overlap layers for device active area )
 ;( ------------------------------------- )
 ) ;dlrDevices

) ;dlrRules


;********************************
; LAS RULES
;********************************
lasRules(

 lasProperties(
 ;( propName                    propValue     )
 ;( --------                    ---------     )
  ( lasPrimitiveList    	"pmos nmos"          )
  ( lasSwitchViewList   	"schematic cmos_sch" )
 ) ;lasProperties

) ;lasRules
